# 미세먼지 지역별 전처리

- [데이터 출처 : 에어코리아](https://www.airkorea.or.kr/web/pmRelay?itemCode=11008&pMENU_NO=109)

## 라이브러리 및 데이터 불러오기

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [23]:
import pandas as pd
import numpy as np
import os
from datetime import datetime, timedelta
from tqdm import tqdm

In [6]:
path_dir = '/content/gdrive/MyDrive/aiffel-hackathon/data/weather/미세먼지'
file_list = os.listdir(path_dir)

In [8]:
file_list

['19년 울산 미세먼지 데이터 (1).xls',
 '19년 울산 미세먼지 데이터 (2).xls',
 '19년 울산 미세먼지 데이터 (3).xls',
 '19년 울산 미세먼지 데이터 (4).xls',
 '19년 울산 미세먼지 데이터 (5).xls',
 '19년 울산 미세먼지 데이터 (6).xls',
 '19년 울산 미세먼지 데이터 (7).xls',
 '19년 울산 미세먼지 데이터 (8).xls',
 '19년 울산 미세먼지 데이터 (9).xls',
 '19년 울산 미세먼지 데이터 (10).xls',
 '19년 울산 미세먼지 데이터 (11).xls',
 '19년 세종 미세먼지 데이터 (1).xls',
 '19년 세종 미세먼지 데이터 (2).xls',
 '19년 세종 미세먼지 데이터 (3).xls',
 '19년 세종 미세먼지 데이터 (4).xls',
 '19년 세종 미세먼지 데이터 (5).xls',
 '19년 세종 미세먼지 데이터 (6).xls',
 '19년 세종 미세먼지 데이터 (7).xls',
 '19년 세종 미세먼지 데이터 (8).xls',
 '19년 세종 미세먼지 데이터 (9).xls',
 '19년 세종 미세먼지 데이터 (10).xls',
 '19년 세종 미세먼지 데이터 (11).xls']

## 세종시 미세먼지 데이터 전처리

### 데이터 불러오기

In [195]:
sejong01 = pd.read_excel(path_dir + '/19년 세종 미세먼지 데이터 (1).xls', header=3)
sejong02 = pd.read_excel(path_dir + '/19년 세종 미세먼지 데이터 (2).xls', header=3)
sejong03 = pd.read_excel(path_dir + '/19년 세종 미세먼지 데이터 (3).xls', header=3)
sejong04 = pd.read_excel(path_dir + '/19년 세종 미세먼지 데이터 (4).xls', header=3)
sejong05 = pd.read_excel(path_dir + '/19년 세종 미세먼지 데이터 (5).xls', header=3)
sejong06 = pd.read_excel(path_dir + '/19년 세종 미세먼지 데이터 (6).xls', header=3)
sejong07 = pd.read_excel(path_dir + '/19년 세종 미세먼지 데이터 (7).xls', header=3)
sejong08 = pd.read_excel(path_dir + '/19년 세종 미세먼지 데이터 (8).xls', header=3)
sejong09 = pd.read_excel(path_dir + '/19년 세종 미세먼지 데이터 (9).xls', header=3)
sejong10 = pd.read_excel(path_dir + '/19년 세종 미세먼지 데이터 (10).xls', header=3)
sejong11 = pd.read_excel(path_dir + '/19년 세종 미세먼지 데이터 (11).xls', header=3)

In [196]:
sejong01.head(1)

    측정망         측정소명  1일  2일  3일  4일  5일  ...  25일  26일  27일  28일  29일  30일  31일
0  도시대기  [세종 세종시]부강면 NaN  39  53  79  66  ...   51   48   44   66   86   79   60

[1 rows x 33 columns]

In [197]:
# 1월 데이터 전처리
def preprocess_01(df):
  
  df = df.drop('측정망', axis=1)
  df = df.melt(id_vars='측정소명')

  df.columns = ['region', 'day', 'pm10']

  df['region'] = df['region'].str.replace('[',"")
  df['region'] = df['region'].str.split(']', expand=True)[0]

  df['month'] = '2019-01'  ## 월정보만 임의로 변경해주면 됩니다.
  df['day'] = df['day'].str.replace('일','')
  df['date'] = df['month'] + '-' + df['day']
  df['date'] = pd.to_datetime(df['date'])
  df = df.drop(['day','month'], axis=1)

  df = df.groupby(['region', 'date'])['pm10'].mean().reset_index()
  df = df.rename(columns={'date':'day'})

  return df


# 2월 데이터 전처리
def preprocess_02(df):
    
  df = df.drop('측정망', axis=1)
  df = df.melt(id_vars='측정소명')

  df.columns = ['region', 'day', 'pm10']

  df['region'] = df['region'].str.replace('[',"")
  df['region'] = df['region'].str.split(']', expand=True)[0]

  df['month'] = '2019-02'  ## 월정보만 임의로 변경해주면 됩니다.
  df['day'] = df['day'].str.replace('일','')
  df['date'] = df['month'] + '-' + df['day']
  df['date'] = pd.to_datetime(df['date'])
  df = df.drop(['day','month'], axis=1)

  df = df.groupby(['region', 'date'])['pm10'].mean().reset_index()
  df = df.rename(columns={'date':'day'})

  return df


# 3월 데이터 전처리
def preprocess_03(df):
    
  df = df.drop('측정망', axis=1)
  df = df.melt(id_vars='측정소명')

  df.columns = ['region', 'day', 'pm10']

  df['region'] = df['region'].str.replace('[',"")
  df['region'] = df['region'].str.split(']', expand=True)[0]

  df['month'] = '2019-03'  ## 월정보만 임의로 변경해주면 됩니다.
  df['day'] = df['day'].str.replace('일','')
  df['date'] = df['month'] + '-' + df['day']
  df['date'] = pd.to_datetime(df['date'])
  df = df.drop(['day','month'], axis=1)

  df = df.groupby(['region', 'date'])['pm10'].mean().reset_index()
  df = df.rename(columns={'date':'day'})

  return df


# 4월 데이터 전처리
def preprocess_04(df):
    
  df = df.drop('측정망', axis=1)
  df = df.melt(id_vars='측정소명')

  df.columns = ['region', 'day', 'pm10']

  df['region'] = df['region'].str.replace('[',"")
  df['region'] = df['region'].str.split(']', expand=True)[0]

  df['month'] = '2019-04'  ## 월정보만 임의로 변경해주면 됩니다.
  df['day'] = df['day'].str.replace('일','')
  df['date'] = df['month'] + '-' + df['day']
  df['date'] = pd.to_datetime(df['date'])
  df = df.drop(['day','month'], axis=1)

  df = df.groupby(['region', 'date'])['pm10'].mean().reset_index()
  df = df.rename(columns={'date':'day'})

  return df


# 5월 데이터 전처리
def preprocess_05(df):
    
  df = df.drop('측정망', axis=1)
  df = df.melt(id_vars='측정소명')

  df.columns = ['region', 'day', 'pm10']

  df['region'] = df['region'].str.replace('[',"")
  df['region'] = df['region'].str.split(']', expand=True)[0]

  df['month'] = '2019-05'  ## 월정보만 임의로 변경해주면 됩니다.
  df['day'] = df['day'].str.replace('일','')
  df['date'] = df['month'] + '-' + df['day']
  df['date'] = pd.to_datetime(df['date'])
  df = df.drop(['day','month'], axis=1)

  df = df.groupby(['region', 'date'])['pm10'].mean().reset_index()
  df = df.rename(columns={'date':'day'})

  return df


# 6월 데이터 전처리
def preprocess_06(df):
    
  df = df.drop('측정망', axis=1)
  df = df.melt(id_vars='측정소명')

  df.columns = ['region', 'day', 'pm10']

  df['region'] = df['region'].str.replace('[',"")
  df['region'] = df['region'].str.split(']', expand=True)[0]

  df['month'] = '2019-06'  ## 월정보만 임의로 변경해주면 됩니다.
  df['day'] = df['day'].str.replace('일','')
  df['date'] = df['month'] + '-' + df['day']
  df['date'] = pd.to_datetime(df['date'])
  df = df.drop(['day','month'], axis=1)

  df = df.groupby(['region', 'date'])['pm10'].mean().reset_index()
  df = df.rename(columns={'date':'day'})

  return df


# 7월 데이터 전처리
def preprocess_07(df):
    
  df = df.drop('측정망', axis=1)
  df = df.melt(id_vars='측정소명')

  df.columns = ['region', 'day', 'pm10']

  df['region'] = df['region'].str.replace('[',"")
  df['region'] = df['region'].str.split(']', expand=True)[0]

  df['month'] = '2019-07'  ## 월정보만 임의로 변경해주면 됩니다.
  df['day'] = df['day'].str.replace('일','')
  df['date'] = df['month'] + '-' + df['day']
  df['date'] = pd.to_datetime(df['date'])
  df = df.drop(['day','month'], axis=1)

  df = df.groupby(['region', 'date'])['pm10'].mean().reset_index()
  df = df.rename(columns={'date':'day'})

  return df


# 8월 데이터 전처리
def preprocess_08(df):
    
  df = df.drop('측정망', axis=1)
  df = df.melt(id_vars='측정소명')

  df.columns = ['region', 'day', 'pm10']

  df['region'] = df['region'].str.replace('[',"")
  df['region'] = df['region'].str.split(']', expand=True)[0]

  df['month'] = '2019-08'  ## 월정보만 임의로 변경해주면 됩니다.
  df['day'] = df['day'].str.replace('일','')
  df['date'] = df['month'] + '-' + df['day']
  df['date'] = pd.to_datetime(df['date'])
  df = df.drop(['day','month'], axis=1)

  df = df.groupby(['region', 'date'])['pm10'].mean().reset_index()
  df = df.rename(columns={'date':'day'})

  return df
  

# 9월 데이터 전처리
def preprocess_09(df):
    
  df = df.drop('측정망', axis=1)
  df = df.melt(id_vars='측정소명')

  df.columns = ['region', 'day', 'pm10']

  df['region'] = df['region'].str.replace('[',"")
  df['region'] = df['region'].str.split(']', expand=True)[0]

  df['month'] = '2019-09'  ## 월정보만 임의로 변경해주면 됩니다.
  df['day'] = df['day'].str.replace('일','')
  df['date'] = df['month'] + '-' + df['day']
  df['date'] = pd.to_datetime(df['date'])
  df = df.drop(['day','month'], axis=1)

  df = df.groupby(['region', 'date'])['pm10'].mean().reset_index()
  df = df.rename(columns={'date':'day'})

  return df


# 10월 데이터 전처리
def preprocess_10(df):
    
  df = df.drop('측정망', axis=1)
  df = df.melt(id_vars='측정소명')

  df.columns = ['region', 'day', 'pm10']

  df['region'] = df['region'].str.replace('[',"")
  df['region'] = df['region'].str.split(']', expand=True)[0]

  df['month'] = '2019-10'  ## 월정보만 임의로 변경해주면 됩니다.
  df['day'] = df['day'].str.replace('일','')
  df['date'] = df['month'] + '-' + df['day']
  df['date'] = pd.to_datetime(df['date'])
  df = df.drop(['day','month'], axis=1)

  df = df.groupby(['region', 'date'])['pm10'].mean().reset_index()
  df = df.rename(columns={'date':'day'})

  return df


# 11월 데이터 전처리
def preprocess_11(df):
    
  df = df.drop('측정망', axis=1)
  df = df.melt(id_vars='측정소명')

  df.columns = ['region', 'day', 'pm10']

  df['region'] = df['region'].str.replace('[',"")
  df['region'] = df['region'].str.split(']', expand=True)[0]

  df['month'] = '2019-11'  ## 월정보만 임의로 변경해주면 됩니다.
  df['day'] = df['day'].str.replace('일','')
  df['date'] = df['month'] + '-' + df['day']
  df['date'] = pd.to_datetime(df['date'])
  df = df.drop(['day','month'], axis=1)

  df = df.groupby(['region', 'date'])['pm10'].mean().reset_index()
  df = df.rename(columns={'date':'day'})

  return df


# 12월 데이터 전처리
def preprocess_12(df):
    
  df = df.drop('측정망', axis=1)
  df = df.melt(id_vars='측정소명')

  df.columns = ['region', 'day', 'pm10']

  df['region'] = df['region'].str.replace('[',"")
  df['region'] = df['region'].str.split(']', expand=True)[0]

  df['month'] = '2019-12'  ## 월정보만 임의로 변경해주면 됩니다.
  df['day'] = df['day'].str.replace('일','')
  df['date'] = df['month'] + '-' + df['day']
  df['date'] = pd.to_datetime(df['date'])
  df = df.drop(['day','month'], axis=1)

  df = df.groupby(['region', 'date'])['pm10'].mean().reset_index()
  df = df.rename(columns={'date':'day'})

  return df

In [198]:
sejong01 = preprocess_01(sejong01)
sejong01

    region        day    pm10
0   세종 세종시 2019-01-01     NaN
1   세종 세종시 2019-01-02   38.00
2   세종 세종시 2019-01-03   46.75
3   세종 세종시 2019-01-04   65.25
4   세종 세종시 2019-01-05   60.25
5   세종 세종시 2019-01-06   52.75
6   세종 세종시 2019-01-07   67.25
7   세종 세종시 2019-01-08   64.00
8   세종 세종시 2019-01-09   59.00
9   세종 세종시 2019-01-10   62.50
10  세종 세종시 2019-01-11   84.50
11  세종 세종시 2019-01-12  110.00
12  세종 세종시 2019-01-13  110.75
13  세종 세종시 2019-01-14  168.50
14  세종 세종시 2019-01-15  139.25
15  세종 세종시 2019-01-16   51.75
16  세종 세종시 2019-01-17   43.75
17  세종 세종시 2019-01-18   81.25
18  세종 세종시 2019-01-19  113.50
19  세종 세종시 2019-01-20   65.75
20  세종 세종시 2019-01-21   39.50
21  세종 세종시 2019-01-22   65.00
22  세종 세종시 2019-01-23   79.00
23  세종 세종시 2019-01-24   45.00
24  세종 세종시 2019-01-25   46.75
25  세종 세종시 2019-01-26   45.50
26  세종 세종시 2019-01-27   41.00
27  세종 세종시 2019-01-28   64.75
28  세종 세종시 2019-01-29   77.50
29  세종 세종시 2019-01-30   69.50
30  세종 세종시 2019-01-31   56.75

In [199]:
sejong02 = preprocess_02(sejong02)
sejong02

    region        day        pm10
0   세종 세종시 2019-02-01   40.000000
1   세종 세종시 2019-02-02   68.000000
2   세종 세종시 2019-02-03   49.750000
3   세종 세종시 2019-02-04   75.750000
4   세종 세종시 2019-02-05   90.500000
5   세종 세종시 2019-02-06   91.000000
6   세종 세종시 2019-02-07   60.500000
7   세종 세종시 2019-02-08   34.000000
8   세종 세종시 2019-02-09   35.750000
9   세종 세종시 2019-02-10   42.000000
10  세종 세종시 2019-02-11   35.000000
11  세종 세종시 2019-02-12   59.250000
12  세종 세종시 2019-02-13   63.750000
13  세종 세종시 2019-02-14   55.000000
14  세종 세종시 2019-02-15   62.750000
15  세종 세종시 2019-02-16   53.250000
16  세종 세종시 2019-02-17   47.333333
17  세종 세종시 2019-02-18   48.500000
18  세종 세종시 2019-02-19   50.250000
19  세종 세종시 2019-02-20   64.000000
20  세종 세종시 2019-02-21   99.000000
21  세종 세종시 2019-02-22  108.500000
22  세종 세종시 2019-02-23   84.000000
23  세종 세종시 2019-02-24   57.000000
24  세종 세종시 2019-02-25   85.750000
25  세종 세종시 2019-02-26   57.500000
26  세종 세종시 2019-02-27   70.750000
27  세종 세종시 2019-02-28  115.500000

In [200]:
sejong03 = preprocess_03(sejong03)
sejong03

    region        day    pm10
0   세종 세종시 2019-03-01  177.00
1   세종 세종시 2019-03-02  121.50
2   세종 세종시 2019-03-03  127.50
3   세종 세종시 2019-03-04  158.00
4   세종 세종시 2019-03-05  206.25
5   세종 세종시 2019-03-06  153.00
6   세종 세종시 2019-03-07   91.25
7   세종 세종시 2019-03-08   56.75
8   세종 세종시 2019-03-09   55.75
9   세종 세종시 2019-03-10   55.25
10  세종 세종시 2019-03-11   39.00
11  세종 세종시 2019-03-12   65.25
12  세종 세종시 2019-03-13   36.25
13  세종 세종시 2019-03-14   42.50
14  세종 세종시 2019-03-15   42.75
15  세종 세종시 2019-03-16   35.50
16  세종 세종시 2019-03-17   36.75
17  세종 세종시 2019-03-18   36.50
18  세종 세종시 2019-03-19   62.50
19  세종 세종시 2019-03-20   87.50
20  세종 세종시 2019-03-21   25.75
21  세종 세종시 2019-03-22   38.25
22  세종 세종시 2019-03-23   26.00
23  세종 세종시 2019-03-24   27.75
24  세종 세종시 2019-03-25   50.75
25  세종 세종시 2019-03-26   46.25
26  세종 세종시 2019-03-27   77.25
27  세종 세종시 2019-03-28   79.25
28  세종 세종시 2019-03-29   51.00
29  세종 세종시 2019-03-30   41.50
30  세종 세종시 2019-03-31   36.50

In [201]:
sejong04 = preprocess_04(sejong04)
sejong04

    region        day   pm10
0   세종 세종시 2019-04-01  26.50
1   세종 세종시 2019-04-02  29.75
2   세종 세종시 2019-04-03  37.00
3   세종 세종시 2019-04-04  42.75
4   세종 세종시 2019-04-05  73.25
5   세종 세종시 2019-04-06  67.50
6   세종 세종시 2019-04-07  46.00
7   세종 세종시 2019-04-08  43.00
8   세종 세종시 2019-04-09  27.25
9   세종 세종시 2019-04-10  12.75
10  세종 세종시 2019-04-11  36.00
11  세종 세종시 2019-04-12  41.25
12  세종 세종시 2019-04-13  41.50
13  세종 세종시 2019-04-14  47.00
14  세종 세종시 2019-04-15  53.75
15  세종 세종시 2019-04-16  56.75
16  세종 세종시 2019-04-17  47.00
17  세종 세종시 2019-04-18  33.00
18  세종 세종시 2019-04-19  53.75
19  세종 세종시 2019-04-20  42.75
20  세종 세종시 2019-04-21  52.50
21  세종 세종시 2019-04-22  59.75
22  세종 세종시 2019-04-23  49.25
23  세종 세종시 2019-04-24  21.75
24  세종 세종시 2019-04-25  45.00
25  세종 세종시 2019-04-26  15.25
26  세종 세종시 2019-04-27  17.50
27  세종 세종시 2019-04-28  28.25
28  세종 세종시 2019-04-29  32.25
29  세종 세종시 2019-04-30  27.50

In [202]:
sejong05 = preprocess_05(sejong05)
sejong05

    region        day   pm10
0   세종 세종시 2019-05-01  60.25
1   세종 세종시 2019-05-02  68.50
2   세종 세종시 2019-05-03  46.50
3   세종 세종시 2019-05-04  81.00
4   세종 세종시 2019-05-05  62.50
5   세종 세종시 2019-05-06  43.50
6   세종 세종시 2019-05-07  42.50
7   세종 세종시 2019-05-08  48.75
8   세종 세종시 2019-05-09  44.25
9   세종 세종시 2019-05-10  51.50
10  세종 세종시 2019-05-11  57.00
11  세종 세종시 2019-05-12  49.50
12  세종 세종시 2019-05-13  53.75
13  세종 세종시 2019-05-14  57.75
14  세종 세종시 2019-05-15  80.50
15  세종 세종시 2019-05-16  82.00
16  세종 세종시 2019-05-17  58.25
17  세종 세종시 2019-05-18  21.75
18  세종 세종시 2019-05-19  20.50
19  세종 세종시 2019-05-20  33.75
20  세종 세종시 2019-05-21  42.00
21  세종 세종시 2019-05-22  52.00
22  세종 세종시 2019-05-23  65.00
23  세종 세종시 2019-05-24  87.00
24  세종 세종시 2019-05-25  73.25
25  세종 세종시 2019-05-26  38.50
26  세종 세종시 2019-05-27  21.50
27  세종 세종시 2019-05-28  23.25
28  세종 세종시 2019-05-29  35.25
29  세종 세종시 2019-05-30  47.75
30  세종 세종시 2019-05-31  21.50

In [203]:
sejong06 = preprocess_06(sejong06)
sejong06

    region        day   pm10
0   세종 세종시 2019-06-01  27.25
1   세종 세종시 2019-06-02  37.25
2   세종 세종시 2019-06-03  48.75
3   세종 세종시 2019-06-04  46.25
4   세종 세종시 2019-06-05  55.75
5   세종 세종시 2019-06-06  59.75
6   세종 세종시 2019-06-07  12.00
7   세종 세종시 2019-06-08  23.75
8   세종 세종시 2019-06-09  37.50
9   세종 세종시 2019-06-10  13.75
10  세종 세종시 2019-06-11  22.25
11  세종 세종시 2019-06-12  37.00
12  세종 세종시 2019-06-13  38.75
13  세종 세종시 2019-06-14  57.50
14  세종 세종시 2019-06-15  31.00
15  세종 세종시 2019-06-16  31.75
16  세종 세종시 2019-06-17  26.00
17  세종 세종시 2019-06-18  30.00
18  세종 세종시 2019-06-19  44.25
19  세종 세종시 2019-06-20  35.50
20  세종 세종시 2019-06-21  35.50
21  세종 세종시 2019-06-22  32.25
22  세종 세종시 2019-06-23  20.75
23  세종 세종시 2019-06-24  30.25
24  세종 세종시 2019-06-25  33.00
25  세종 세종시 2019-06-26  36.25
26  세종 세종시 2019-06-27  27.25
27  세종 세종시 2019-06-28  30.00
28  세종 세종시 2019-06-29  24.00
29  세종 세종시 2019-06-30  29.00

In [204]:
sejong07 = preprocess_07(sejong07)
sejong07

    region        day   pm10
0   세종 세종시 2019-07-01  32.50
1   세종 세종시 2019-07-02  26.75
2   세종 세종시 2019-07-03  42.00
3   세종 세종시 2019-07-04  39.50
4   세종 세종시 2019-07-05  35.75
5   세종 세종시 2019-07-06  29.50
6   세종 세종시 2019-07-07  19.50
7   세종 세종시 2019-07-08  13.50
8   세종 세종시 2019-07-09  12.75
9   세종 세종시 2019-07-10  11.00
10  세종 세종시 2019-07-11  13.50
11  세종 세종시 2019-07-12  18.00
12  세종 세종시 2019-07-13  29.25
13  세종 세종시 2019-07-14  35.75
14  세종 세종시 2019-07-15  40.25
15  세종 세종시 2019-07-16  28.50
16  세종 세종시 2019-07-17  36.00
17  세종 세종시 2019-07-18  25.75
18  세종 세종시 2019-07-19  15.25
19  세종 세종시 2019-07-20   7.75
20  세종 세종시 2019-07-21  18.50
21  세종 세종시 2019-07-22  25.00
22  세종 세종시 2019-07-23  20.75
23  세종 세종시 2019-07-24  20.75
24  세종 세종시 2019-07-25  18.50
25  세종 세종시 2019-07-26  24.00
26  세종 세종시 2019-07-27  17.50
27  세종 세종시 2019-07-28  14.50
28  세종 세종시 2019-07-29  16.00
29  세종 세종시 2019-07-30  14.75
30  세종 세종시 2019-07-31  12.50

In [205]:
sejong08 = preprocess_08(sejong08)
sejong08

    region        day   pm10
0   세종 세종시 2019-08-01  14.25
1   세종 세종시 2019-08-02  19.75
2   세종 세종시 2019-08-03  28.25
3   세종 세종시 2019-08-04  40.75
4   세종 세종시 2019-08-05  52.50
5   세종 세종시 2019-08-06  31.75
6   세종 세종시 2019-08-07  26.25
7   세종 세종시 2019-08-08  32.25
8   세종 세종시 2019-08-09  23.25
9   세종 세종시 2019-08-10  34.25
10  세종 세종시 2019-08-11  19.00
11  세종 세종시 2019-08-12  19.00
12  세종 세종시 2019-08-13  24.00
13  세종 세종시 2019-08-14  19.00
14  세종 세종시 2019-08-15  11.50
15  세종 세종시 2019-08-16  21.50
16  세종 세종시 2019-08-17  36.00
17  세종 세종시 2019-08-18  27.25
18  세종 세종시 2019-08-19  33.75
19  세종 세종시 2019-08-20  32.00
20  세종 세종시 2019-08-21  34.00
21  세종 세종시 2019-08-22  38.25
22  세종 세종시 2019-08-23  36.25
23  세종 세종시 2019-08-24  30.00
24  세종 세종시 2019-08-25  20.00
25  세종 세종시 2019-08-26  22.00
26  세종 세종시 2019-08-27  18.00
27  세종 세종시 2019-08-28  25.00
28  세종 세종시 2019-08-29  26.50
29  세종 세종시 2019-08-30  19.25
30  세종 세종시 2019-08-31  22.25

In [206]:
sejong09 = preprocess_09(sejong09)
sejong09

    region        day       pm10
0   세종 세종시 2019-09-01  24.250000
1   세종 세종시 2019-09-02  27.500000
2   세종 세종시 2019-09-03  14.250000
3   세종 세종시 2019-09-04  13.500000
4   세종 세종시 2019-09-05  17.000000
5   세종 세종시 2019-09-06  22.750000
6   세종 세종시 2019-09-07  15.750000
7   세종 세종시 2019-09-08  21.000000
8   세종 세종시 2019-09-09  22.500000
9   세종 세종시 2019-09-10  28.500000
10  세종 세종시 2019-09-11  22.250000
11  세종 세종시 2019-09-12  12.750000
12  세종 세종시 2019-09-13  17.000000
13  세종 세종시 2019-09-14  20.750000
14  세종 세종시 2019-09-15  21.500000
15  세종 세종시 2019-09-16  21.500000
16  세종 세종시 2019-09-17  20.500000
17  세종 세종시 2019-09-18  29.666667
18  세종 세종시 2019-09-19  34.666667
19  세종 세종시 2019-09-20  26.250000
20  세종 세종시 2019-09-21  14.000000
21  세종 세종시 2019-09-22   5.000000
22  세종 세종시 2019-09-23  11.250000
23  세종 세종시 2019-09-24  23.750000
24  세종 세종시 2019-09-25  32.000000
25  세종 세종시 2019-09-26  24.750000
26  세종 세종시 2019-09-27  28.000000
27  세종 세종시 2019-09-28  43.666667
28  세종 세종시 2019-09-29  42.333333
29  세종 세종시 2019-09-30  45.750000

In [207]:
sejong10 = preprocess_10(sejong10)
sejong10

    region        day   pm10
0   세종 세종시 2019-10-01  44.00
1   세종 세종시 2019-10-02  18.75
2   세종 세종시 2019-10-03  13.00
3   세종 세종시 2019-10-04  29.75
4   세종 세종시 2019-10-05  42.00
5   세종 세종시 2019-10-06  13.25
6   세종 세종시 2019-10-07  12.75
7   세종 세종시 2019-10-08  21.75
8   세종 세종시 2019-10-09  27.00
9   세종 세종시 2019-10-10  41.50
10  세종 세종시 2019-10-11  50.25
11  세종 세종시 2019-10-12  30.00
12  세종 세종시 2019-10-13  23.00
13  세종 세종시 2019-10-14  33.50
14  세종 세종시 2019-10-15  28.25
15  세종 세종시 2019-10-16  28.50
16  세종 세종시 2019-10-17  32.75
17  세종 세종시 2019-10-18  28.00
18  세종 세종시 2019-10-19  27.75
19  세종 세종시 2019-10-20  37.75
20  세종 세종시 2019-10-21  42.00
21  세종 세종시 2019-10-22  31.50
22  세종 세종시 2019-10-23  40.00
23  세종 세종시 2019-10-24  38.00
24  세종 세종시 2019-10-25  34.75
25  세종 세종시 2019-10-26  27.00
26  세종 세종시 2019-10-27  30.00
27  세종 세종시 2019-10-28  38.25
28  세종 세종시 2019-10-29  63.50
29  세종 세종시 2019-10-30  29.75
30  세종 세종시 2019-10-31  54.00

In [208]:
sejong11 = preprocess_11(sejong11)
sejong11

    region        day   pm10
0   세종 세종시 2019-11-01  86.75
1   세종 세종시 2019-11-02  76.25
2   세종 세종시 2019-11-03  78.00
3   세종 세종시 2019-11-04  26.50
4   세종 세종시 2019-11-05  39.75
5   세종 세종시 2019-11-06  43.25
6   세종 세종시 2019-11-07  43.00
7   세종 세종시 2019-11-08  44.25
8   세종 세종시 2019-11-09  43.50
9   세종 세종시 2019-11-10  50.25
10  세종 세종시 2019-11-11  25.50
11  세종 세종시 2019-11-12  38.00
12  세종 세종시 2019-11-13  43.75
13  세종 세종시 2019-11-14  26.25
14  세종 세종시 2019-11-15  34.50
15  세종 세종시 2019-11-16  48.75
16  세종 세종시 2019-11-17  45.50
17  세종 세종시 2019-11-18  80.50
18  세종 세종시 2019-11-19  31.50
19  세종 세종시 2019-11-20  30.25
20  세종 세종시 2019-11-21  49.25
21  세종 세종시 2019-11-22  49.75
22  세종 세종시 2019-11-23  42.00
23  세종 세종시 2019-11-24  34.25
24  세종 세종시 2019-11-25  28.50
25  세종 세종시 2019-11-26  36.75
26  세종 세종시 2019-11-27  39.50
27  세종 세종시 2019-11-28  46.00
28  세종 세종시 2019-11-29  36.50
29  세종 세종시 2019-11-30  46.50

### 데이터 병합

In [210]:
sejong_pm10 = pd.concat([sejong01, sejong02, sejong03, sejong04,
                         sejong05, sejong06, sejong07, sejong08,
                         sejong09, sejong10, sejong11], axis=0)

    region        day   pm10
0   세종 세종시 2019-01-01    NaN
1   세종 세종시 2019-01-02  38.00
2   세종 세종시 2019-01-03  46.75
3   세종 세종시 2019-01-04  65.25
4   세종 세종시 2019-01-05  60.25
..     ...        ...    ...
25  세종 세종시 2019-11-26  36.75
26  세종 세종시 2019-11-27  39.50
27  세종 세종시 2019-11-28  46.00
28  세종 세종시 2019-11-29  36.50
29  세종 세종시 2019-11-30  46.50

[334 rows x 3 columns]

1월부터 11월까지 세종시의 미세먼지 데이터를 만들어주었습니다.
같은 방법으로 다른 도시의 미세먼지 데이터를 가공해줄 수 있습니다.